### ISSUE TITLE
Crash after receiving phone call

### ISSUE THREAD

**Issue by miekg** [M8s-dev/android_device_htc_m8qlul#12]
Hi, thanks for this work. The rom works well. I installed the rom from (I thought) yesterday. There is one issue were the phone hangs after receiving a call and then slowly crashes (or something). Haven't had the change to investigate (yet).

**Comment by voidzero** [comment]
Thanks for the bug report, this confirms my suspicions, because I had the same thing happen to me in the car today. I'll look into this one as soon as i can; this bug is annoying and does not seem to happen every time. If you figure this out before I do, keep me posted. I had mobile data enabled and wifi disabled when this happened.

**Comment by miekg** [comment]
I have a logcat where I called myself twice and first time it worked, second time the phone went in to a slash crash and rebooted.

**Comment by miekg** [comment]
damn, there is also stuff on stderr, didn't capture that... Posting some stuff here (can't really say if this is just before that reboot though :()

```
I/InCall  (12521): AnswerPresenter - onDecline mCallId:[Ljava.lang.String;@260d72d1phoneId:0
W/linker  (13621): libonlinepromo.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
V/NetParse JNI layer(13621): jniRegisterNativeMethods
V/NetParse JNI layer(13621): Registering uk/co/aifactory/onlinepromo/HelperService natives
I/Watchdog_N(  821): dumpKernelStacks
W/Watchdog(  821): *** WATCHDOG KILLING SYSTEM PROCESS: Blocked in handler on main thread (main)
W/Watchdog(  821): main thread stack trace:
W/Watchdog(  821):     at android.media.AudioSystem.setPhoneState(Native Method)
W/Watchdog(  821):     at android.media.AudioService.setModeInt(AudioService.java:2385)
W/Watchdog(  821):     at android.media.AudioService.setMode(AudioService.java:2321)
W/Watchdog(  821):     at android.media.AudioManager.setMode(AudioManager.java:1790)
W/Watchdog(  821):     at com.android.server.telecom.CallAudioManager.setMode(CallAudioManager.java:484)
W/Watchdog(  821):     at com.android.server.telecom.CallAudioManager.requestAudioFocusAndSetMode(CallAudioManager.java:435)
W/Watchdog(  821):     at com.android.server.telecom.CallAudioManager.updateAudioStreamAndMode(CallAudioManager.java:402)
W/Watchdog(  821):     at com.android.server.telecom.CallAudioManager.setIsRinging(CallAudioManager.java:247)
W/Watchdog(  821):     at com.android.server.telecom.CallAudioManager.onIncomingCallAnswered(CallAudioManager.java:124)
W/Watchdog(  821):     at com.android.server.telecom.CallsManager.answerCall(CallsManager.java:794)
W/Watchdog(  821):     at com.android.server.telecom.InCallAdapter$InCallAdapterHandler.handleMessage(InCallAdapter.java:64)
W/Watchdog(  821):     at android.os.Handler.dispatchMessage(Handler.java:102)
W/Watchdog(  821):     at android.os.Looper.loop(Looper.java:135)
W/Watchdog(  821):     at com.android.server.SystemServer.run(SystemServer.java:298)
W/Watchdog(  821):     at com.android.server.SystemServer.main(SystemServer.java:186)
W/Watchdog(  821):     at java.lang.reflect.Method.invoke(Native Method)
W/Watchdog(  821):     at java.lang.reflect.Method.invoke(Method.java:372)
W/Watchdog(  821):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
W/Watchdog(  821):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
W/Watchdog(  821): *** GOODBYE!
I/Process (  821): Sending signal. PID: 821 SIG: 9
W/Sensors (12521): sensorservice died [0x55a2843fd0]
W/Sensors (13463): sensorservice died [0x55a2845db0]
W/Sensors (13493): sensorservice died [0xab68bdb0]
W/Sensors ( 2051): sensorservice died [0x55a28a0b10]
E/WifiManager(30194): Channel connection lost
E/WifiManager(10565): Channel connection lost
W/Sensors ( 1207): sensorservice died [0x55a298a950]
E/WifiManager(11837): Channel connection lost
E/WifiManager( 2051): Channel connection lost
E/WifiManager( 1698): Channel connection lost
E/WifiManager( 1207): Channel connection lost
W/Sensors (  407): sensorservice died [0xab4711f8]
```

**Comment by miekg** [comment]
I can send the logs privately?

**Comment by voidzero** [comment]
Sorry for delaying my response, sure, send the logs to me privately via email (mark at voidzero • net). I will probably check them after the weekend.

When you have the time also please update to the latest version (151114) to see if that fixes it already, I have high hopes that it does ;)

**Comment by miekg** [comment]
Cool. Will send them shortly. Just upgraded to 151114 :) First breakfast, then I will check if I calling works.

**Comment by miekg** [comment]
Issue seems to be resolved with 151114 \o/

**Comment by voidzero** [comment]
Nice!

I'll wait a few more days and if no new bug reports come in, I'll close it and :shipit:!

**Comment by voidzero** [comment]
Fixed by https://github.com/M8s-dev/android_device_htc_m8qlul/commit/89b23f41ab79cd69ee35f0a228324a58913423cc
