### ISSUE TITLE
no push notifications

### ISSUE THREAD

**Issue by miekg** [M8s-dev/android_device_htc_m8qlul#14]
After a factory reset (with the image from the 14th), I still can't receive push notifications for apps like hangouts and whatsapp.

I only get notifications when I open the specific app.

This also seems to have hit me with the older images.

**Comment by miekg** [comment]
From `logcat`

```
/GCM     ( 3159): GcmService start Intent { act=com.google.android.gms.gcm.PACKAGE_REPLACED cmp=com.google.android.gms/.gcm.GcmService (has extras) } com.google.android.gms.gcm.PACKAGE_REPLACED
I/ActivityManager(  921): Start proc 5573:com.android.chrome/u0a40 for service com.android.chrome/com.google.ipc.invalidation.ticl.android2.channel.GcmRegistrationTaskService
I/GCM     ( 3159): GCM message GSYNC_TICKLE 0:1447588995342759%e7a7135331877609
D/GCM     ( 3159): GcmService start Intent { act=com.google.android.gcm.intent.SEND flg=0x10 pkg=com.google.android.gms cmp=com.google.android.gms/.gcm.GcmService (has extras) } com.google.android.gcm.intent.SEND


D/GCM     ( 3159): GcmService start Intent { act=com.google.android.gcm.intent.SEND flg=0x10 pkg=com.google.android.gms cmp=com.google.android.gms/.gcm.GcmService (has extras) } com.google.android.gcm.intent.SEND
```

Seems GCM is working (i.e. not crashing)..

**Comment by miekg** [comment]
Sending myself IMs and logcatting yeild these:

```
D/HDKLib0Util( 6669): NoSuchMethodException
E/EasyAccessService_BidataUtil( 6669): mKeyguardContext == null
D/HtcUPManager( 6669): HtcUPEnableChecker Is UP data enable: false
D/HtcUPManager( 6669): hasSameSignatureAsHsp Fail to get info of com.htc.sense.hsp, message: com.htc.sense.hsp
D/HtcUPManager( 6669): HtcUPServiceProxy same signature: false, currernt state: DISCONNECTED
D/HtcUPManager( 6669): HtcUPServiceProxy [init] Package: com.htc.sense.easyaccessservice --> UP data enable: false, dipatch self: false, currernt state: CONNECTED_LOCAL
D/HtcUPManager( 6669): HtcUPUploadScheduler Dispatch period: 86400000 ms
D/HtcUPManager( 6669): HtcUPUploadScheduler Last request upload time: 1447584455630
D/HtcUPManager( 6669): HtcUPUploadScheduler Last upload time: 1447584455630
E/GooglePlayServicesUtil( 6669): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
E/HtcUPManager( 6669): HtcUPHandler.Failed to install dynamic security provider.
E/HtcUPManager( 6669): java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 5089000 but found 0.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
E/HtcUPManager( 6669):  at com.google.android.gms.common.GooglePlayServicesUtil.A(Unknown Source)
E/HtcUPManager( 6669):  at com.google.android.gms.common.GooglePlayServicesUtil.isGooglePlayServicesAvailable(Unknown Source)
E/HtcUPManager( 6669):  at com.google.android.gms.common.GooglePlayServicesUtil.z(Unknown Source)
E/HtcUPManager( 6669):  at com.google.android.gms.security.ProviderInstaller.installIfNeeded(Unknown Source)
E/HtcUPManager( 6669):  at com.htc.lib1.upm.HtcUPHandler.installSecurityProvider(Unknown Source)
E/HtcUPManager( 6669):  at com.htc.lib1.upm.HtcUPHandler.handleMessageInternal(Unknown Source)
E/HtcUPManager( 6669):  at com.htc.lib1.upm.HtcUPHandler.handleMessage(Unknown Source)
E/HtcUPManager( 6669):  at android.os.Handler.dispatchMessage(Handler.java:102)
E/HtcUPManager( 6669):  at android.os.Looper.loop(Looper.java:135)
E/HtcUPManager( 6669):  at android.os.HandlerThread.run(HandlerThread.java:61)
D/HtcUPManager( 6669): HtcUPHandler UP data has been disabled by user
D/audio_hw_primary(  427): out_standby: enter: stream (0xaaf46af0) usecase(1: low-latency-playback)
D/hardware_info(  427): hw_info_append_hw_type : device_name = speaker
E/WifiStateMachine(  921): WifiStateMachine L2Connected CMD_START_SCAN source -2 147, 148 -> obsolete
```

Where

```
E/HtcUPManager( 6669):  at com.google.android.gms.common.GooglePlayServicesUtil.isGooglePlayServicesAvailable(Unknown Source)
```

and

```
E/GooglePlayServicesUtil( 6669): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
```

look strange (but again, not sure what I am looking for here)

**Comment by miekg** [comment]
```
W/GCM     ( 3159): Heartbeat timeout, GCM connection reset -55
```

**Comment by miekg** [comment]
GoogePlayServiceUtil seems a red herring. https://code.google.com/p/google-plus-platform/issues/detail?id=755

**Comment by miekg** [comment]
According to the app 'push notification checking-fix' I should be OK in receiving notifications.

**Comment by miekg** [comment]
Setting "Battery" to "Performance" does not make a difference.

**Comment by miekg** [comment]
No idea, but used different google apps (stock, instead of nano) and factory wiped stuff and that seems to have worked... _strange_, see http://forum.xda-developers.com/showpost.php?p=63838199&postcount=451

**Comment by voidzero** [comment]
I'm also having some problems with the accounts not updating. I noticed it with Pushover mainly (notifications app). I'm glad you found a fix. I'll look into this when I'm feeling better, sadly right now I'm under the weather.

**Comment by voidzero** [comment]
Seems to be a problem with certain versions of gapps. Radio and/or wifi dropping a connection is a different issue altogether, still looking into that. But specifically GCM is gapps related, so out of scope for this device tree.
